# Generated by Django 4.2.15 on 2024-09-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_created',
            field=models.DateTimeField(blank=True),
        ),
    ]
